In [10]:
import numpy as np

# Basic Array Creation

In [15]:
arr = np.array([1,2,3,4])
arr

array(['1', '2', '3.5', 'hey'], dtype='<U32')

In [17]:
a = [1,2,3.5,]
a

[1, 2, 3.5]

In [18]:
np.array(a)

array([1. , 2. , 3.5])

In [20]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array generation function

In [24]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [29]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
arr = np.linspace(0,5,3)
arr

array([0. , 2.5, 5. ])

# Random Generation function

In [41]:
np.random.rand(5)

array([0.0257339 , 0.74371169, 0.84829389, 0.16035728, 0.40632377])

In [49]:
np.random.randn(10)

array([-1.283551  ,  0.23318995, -0.3165635 ,  0.06453017, -0.2448407 ,
       -0.00726417, -0.5637267 , -0.82760107, -1.56965833,  2.16915322])

In [60]:
np.random.randint(10,20,10)

array([19, 11, 10, 14, 18, 19, 18, 10, 16, 14])

# Array Attributes

In [62]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr.shape

(3, 3)

In [64]:

arr.size

9

In [65]:

arr.dtype

dtype('int32')

# Array Methods

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr.min()

1

In [68]:
arr.max()

9

In [69]:
arr.sum()

45

In [76]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [77]:
arr.mean()

5.0

In [78]:
arr.std()

2.581988897471611

In [79]:
arr.argmax()

8

In [80]:
arr.argmin()

0

# Reshaping and Resizing

In [82]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [84]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])