In [1]:
import numpy as np

#### Array Operations

*Arithmetic Operations*

In [7]:
a1 = np.arange(1,6)
a1
a2 = np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [9]:
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

In [11]:
diff = a2 - a1
diff

array([5, 5, 5, 5, 5])

In [12]:
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [13]:
div = a1 / a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [14]:
floor = a1 // a2
floor

array([0, 0, 0, 0, 0])

In [16]:
exp = a2 ** a1
exp

array([     6,     49,    512,   6561, 100000])

*Broadcasting*

In [20]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [21]:
arr + 10

array([20, 30, 40, 50])

In [23]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [25]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

*Deep and Shallow copy*

In [27]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a[4:6] * 10

array([50, 60])

In [42]:
a
b = a.copy()

In [46]:
b[0] = 80

In [47]:
b

array([80,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix Operations*

In [49]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])


In [50]:
A

array([[1, 2],
       [3, 4]])

In [51]:
B

array([[5, 6],
       [7, 8]])

In [53]:
A @ B

array([[19, 22],
       [43, 50]])

In [54]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
A.T

array([[1, 3],
       [2, 4]])

#### Advance Array Manipulation

*Stacking Array*

In [61]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [63]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting Array*

In [67]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [76]:
a = np.vsplit(c, 4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [75]:
for i in a: 
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
