In [1]:
import numpy as np 

#### Valid Sudoku

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]) 

In [3]:
b = np.sum(s, axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [4]:
b
for i in b: 
    if i != 45: 
        print("Sudoku is not Valid")
        break
else:
    print("for rows it is Valid")
        

for rows it is Valid


In [5]:
c = np.sum(s, axis = 0)

In [6]:
c
for i in c: 
    if i != 45: 
        print("Sudoku is not Valid")
        break
else:
    print("for col it is Valid")
        

for col it is Valid


In [7]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [8]:
valid = True

for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]   # extract 3x3 box
        if n.sum() != 45:
            valid = False
            break
    if not valid:
        break

if valid:
    print("Sudoku is valid for 3×3 boxes (by sum check)")
else:
    print("Sudoku is not valid")


Sudoku is valid for 3×3 boxes (by sum check)


In [9]:
s[0:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [10]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

#### General Questions

In [11]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [12]:
#Get the shape of three matrix
data.shape

(5, 3)

In [13]:
#Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [14]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [15]:
#Find the highest Science marks.
scMarks = data[:,2]
np.max(scMarks)

np.int64(95)

In [16]:
#Get details of the student who scored more than 90 in math.
mathMarks = data[:,1]
data[mathMarks > 90]

array([[19, 92, 88]])

In [17]:
#Increase Math marks of all students by 5.
mathMarks = data[:,1]
mathMarks + 5 #Broadcasting

array([90, 97, 81, 70, 95])

In [18]:
#Find how many students are younger than 19.
age = data[:,0]
len(data[age < 19])

3

In [19]:
#Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:], axis=0)
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [20]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)] 

array([[19, 92, 88],
       [20, 90, 85]])

In [21]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])