In [1]:
import numpy as np

In [3]:
# 1. Create a marks dataset
# Create a 2D NumPy array of shape (10, 5)
# 10 students
# 5 subjects
# Marks between 0 and 100
np.random.seed(0)
marks = np.random.randint(0,101,(10,5))
marks

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [10]:
# 2. Calculate total marks of each student
totalMarks = np.sum(marks, axis = 1)
totalMarks

array([289, 236, 316, 325, 292, 257, 380, 130, 202, 195])

In [8]:
# 3. Calculate average marks of each subject
avgMarks = np.mean(marks, axis = 1)
avgMarks

array([57.8, 47.2, 63.2, 65. , 58.4, 51.4, 76. , 26. , 40.4, 39. ])

In [16]:
# 4. Identify the topper (highest total marks)
# first identify idx of highest total marks
topper_idx = np.argmax(totalMarks)
# now show total marks of topper
topperMarks = totalMarks[topper_idx]
topperMarks

380

In [19]:
# 5. Find the subject with the highest average
# first calculate total avg of each sub
avgMarks
# identify idx of highest total avg
highestAvgIdx = np.argmax(avgMarks)
#now show highest avg value
highest_avg = avgMarks[highestAvgIdx]
highest_avg

76.0

In [20]:
# 6. Assign grades
# A: 90 and above
# B: 75–89
# C: 60–74
# D: 40–59
# F: below 40
grades = np.where(avgMarks >= 90, 'A', 
              np.where(avgMarks >= 75, 'B',
              np.where(avgMarks >= 60, 'C',
              np.where(avgMarks >= 40, 'D',
              'F'))))
print("Average Marks:", avgMarks)
print("Grades:", grades)

Average Marks: [57.8 47.2 63.2 65.  58.4 51.4 76.  26.  40.4 39. ]
Grades: ['D' 'D' 'C' 'C' 'D' 'D' 'B' 'F' 'D' 'F']


In [21]:
# 7. Normalize marks between 0 and 1
normalize = avgMarks/100
normalize

array([0.578, 0.472, 0.632, 0.65 , 0.584, 0.514, 0.76 , 0.26 , 0.404,
       0.39 ])