In [2]:
# Create a 1D array from 1 to 20 with a step of 2.
import numpy as np
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
# Make a 5×5 matrix of zeros and set the diagonal values to 1.
arr = np.zeros((5,5))
np.fill_diagonal(arr,1)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr2 = np.zeros((5,5))
for i in range(5):
    arr2[i][i] = 1
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# Create an array of 10 random floats between 0 and 1.
np.random.rand(10)


array([0.69872462, 0.74328731, 0.96982247, 0.47089264, 0.4835769 ,
       0.43900176, 0.93803351, 0.82765523, 0.59156511, 0.87589891])

In [15]:
# Convert a 1D array of 12 elements into a 3×4 array.
arr = np.arange(1,13)
arr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# Given arr = np.array([10,20,30,40,50]), extract the last two elements.
arr = np.array([10,20,30,40,50])
arr[3:]

array([40, 50])

In [25]:
# 6. Slicing
# From arr = np.arange(1,21), get all even numbers using slicing.
arr = np.arange(1,21)
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
# 7. Boolean Masking
# From arr = np.array([3,8,15,24,7,12]), filter values greater than 10.
arr = np.array([3,8,15,24,7,12])
arr[arr > 10]

array([15, 24, 12])

In [30]:
# 8. Fancy Indexing
# Given arr = np.array([10,20,30,40,50]), pick values at positions [0,3,4].
arr = np.array([10,20,30,40,50])
arr[[0,3,4]]

array([10, 40, 50])

In [41]:
# 9. Broadcasting
# Add a 1D array [1,2,3] to every row of a 3×3 matrix.
arr = np.arange(1,10)
arr_2d = arr.reshape((3,3))
arr_1d = np.array([1,2,3])
arr_2d + arr_1d

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [48]:
# 10. Aggregations
# Find the mean, median and standard deviation of [1,2,3,4,5].
arr = np.array([1,2,3,4,5])
mean_arr = np.mean(arr)
median_arr = np.median(arr)
std_arr = np.std(arr)
std_arr

1.4142135623730951

In [52]:
# 11. Argmax / Argmin
# Given arr = np.array([4,99,2,50,7]), find the index of maximum value.
arr = np.array([4,99,2,50,7])
argMax = arr.argmax()
argMin = arr.argmin()
argMin

2

In [55]:
# 12. Unique Values
# Find unique values and their counts from np.array([1,2,2,3,3,3,4]).
arr = np.array([1,2,2,3,3,3,4])
unique_Val, count = np.unique(arr, return_counts=True)
print(unique_Val)
print(count)

[1 2 3 4]
[1 2 3 1]


In [61]:
# 13. Sorting
# Sort this array in descending order: np.array([5,1,7,3,9]).
arr = np.array([9,3,2,5,4,7,1,2])
res = np.sort(arr)[::-1]
res

array([9, 7, 5, 4, 3, 2, 2, 1])

In [64]:
# 14. Concatenate
# Combine two arrays: a=[1,2,3] and b=[4,5,6] into one.
a=[1,2,3]
b=[4,5,6]
res = np.concatenate([a,b])
res

array([1, 2, 3, 4, 5, 6])

In [72]:
# 15. Stack
# Stack two 1D arrays vertically to make a 2×3 matrix.
a=[1,2,3]
b=[4,5,6]
arr_23 = np.vstack((a,b))

In [68]:
# 16. Where()
# Use np.where to replace negative values with 0 in
arr = np.array([4,-3,7,-1,9])
res = np.where(arr < 0, 0 , arr)
print(res)

[4 0 7 0 9]


In [69]:
# 17. Linspace
# Create 10 numbers equally spaced between 0 and 5.
arr = np.linspace(0,5,10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [75]:
# 18. Matrix Multiplication
# Multiply a 2×3 matrix with a 3×2 matrix.
arr = np.arange(1,7)
arr_32 = arr.reshape((3,2))
print(arr_23)
print(arr_32)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [74]:
arr_23 @ arr_32

array([[22, 28],
       [49, 64]])

In [76]:
np.dot(arr_23,arr_32)

array([[22, 28],
       [49, 64]])

In [78]:
#19. Transpose
#Find the transpose of:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
# 20. Flatten
# Convert a 2D array

arr = np.array([[1,2],
                [3,4]])
arr.flatten()

array([1, 2, 3, 4])